version: '3'

services:
  w2m-techtest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
      KAFKA_EXTRA_ARGS: -e advertised.host.name=${HOST_IP}
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"